apiVersion: v1
kind: Service
metadata:
  name: sevice-nginx
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

